version: '2'

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: qiitrend
      POSTGRES_USER: qiitrend
      POSTGRES_PASSWORD: qiitrend
    ports:
      - 5432:5432

  redis:
    image: redis
    ports:
      - 6379:6379

